// Generated by gencpp from file turtle_control_pkg/TurtleVelocity.msg
// DO NOT EDIT!


#ifndef TURTLE_CONTROL_PKG_MESSAGE_TURTLEVELOCITY_H
#define TURTLE_CONTROL_PKG_MESSAGE_TURTLEVELOCITY_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace turtle_control_pkg
{
template <class ContainerAllocator>
struct TurtleVelocity_
{
  typedef TurtleVelocity_<ContainerAllocator> Type;

  TurtleVelocity_()
    : linear_x(0.0)  {
    }
  TurtleVelocity_(const ContainerAllocator& _alloc)
    : linear_x(0.0)  {
  (void)_alloc;
    }



   typedef double _linear_x_type;
  _linear_x_type linear_x;





  typedef boost::shared_ptr< ::turtle_control_pkg::TurtleVelocity_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::turtle_control_pkg::TurtleVelocity_<ContainerAllocator> const> ConstPtr;

}; // struct TurtleVelocity_

typedef ::turtle_control_pkg::TurtleVelocity_<std::allocator<void> > TurtleVelocity;

typedef boost::shared_ptr< ::turtle_control_pkg::TurtleVelocity > TurtleVelocityPtr;
typedef boost::shared_ptr< ::turtle_control_pkg::TurtleVelocity const> TurtleVelocityConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::turtle_control_pkg::TurtleVelocity_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::turtle_control_pkg::TurtleVelocity_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::turtle_control_pkg::TurtleVelocity_<ContainerAllocator1> & lhs, const ::turtle_control_pkg::TurtleVelocity_<ContainerAllocator2> & rhs)
{
  return lhs.linear_x == rhs.linear_x;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::turtle_control_pkg::TurtleVelocity_<ContainerAllocator1> & lhs, const ::turtle_control_pkg::TurtleVelocity_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace turtle_control_pkg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::turtle_control_pkg::TurtleVelocity_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::turtle_control_pkg::TurtleVelocity_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::turtle_control_pkg::TurtleVelocity_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::turtle_control_pkg::TurtleVelocity_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::turtle_control_pkg::TurtleVelocity_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::turtle_control_pkg::TurtleVelocity_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::turtle_control_pkg::TurtleVelocity_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d25d5302321f823414be97fb10f18cdd";
  }

  static const char* value(const ::turtle_control_pkg::TurtleVelocity_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd25d5302321f8234ULL;
  static const uint64_t static_value2 = 0x14be97fb10f18cddULL;
};

template<class ContainerAllocator>
struct DataType< ::turtle_control_pkg::TurtleVelocity_<ContainerAllocator> >
{
  static const char* value()
  {
    return "turtle_control_pkg/TurtleVelocity";
  }

  static const char* value(const ::turtle_control_pkg::TurtleVelocity_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::turtle_control_pkg::TurtleVelocity_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 linear_x\n"
;
  }

  static const char* value(const ::turtle_control_pkg::TurtleVelocity_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::turtle_control_pkg::TurtleVelocity_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.linear_x);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TurtleVelocity_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::turtle_control_pkg::TurtleVelocity_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::turtle_control_pkg::TurtleVelocity_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "linear_x: ";
    Printer<double>::stream(s, indent + "  ", v.linear_x);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TURTLE_CONTROL_PKG_MESSAGE_TURTLEVELOCITY_H
